apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: say-hello
        image: grycap/cowsay
        command: [ "/usr/games/cowsay", "Hello World" ]
      restartPolicy: Never
  backoffLimit: 4
